config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :statuses
  root to: "statuses#index"

  devise_scope :user do 
    get "register",   to: "devise/registrations#new", :as => :register
    get "login",      to: "devise/sessions#new",      :as => :login
    get "logout",     to: "devise/sessions#destroy",  :as => :logout
  end

  get "feed",         to: "statuses#index",            :as => :feed
  get "/:id", to: "profile#show", :as => :profile  

end

app/models/status.rb
class Status < ActiveRecord::Base

	# attr_accessible :user_id,:comment

	validates :comment, presence: true, length:{ minimum:  2 }
	validates :user_id, presence: true

	belongs_to :user

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
 
  has_many :statuses

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :username, presence: true
  validates :username, uniqueness: true
  validates :username, format: {
    with: /^[A-Za-z0-9_-]+$/,
    multiline: true,
    message: "Please format username correctly"
  }

  def fullName
  	first_name+" "+last_name
  end

  def gravatar
    strippedEmail = email.strip
    downcaseEmail = strippedEmail.downcase 
    hash = Digest::MD5.hexdigest(downcaseEmail)
    "http://www.gravatar.com/avatar/#{hash}"
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :first_name, :last_name,:email,:password,:password_confirmation) }
  end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  def show
  	@user = User.find_by_username(params[:id])
  	if @user
  		@statuses = @user.statuses.all
  	else
  		render file:'public/404',status:404,formats:[:html]
  	end
  end

  def profile_params
      params.require(:profile).permit(:id)
    end
end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  before_action :set_status, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!
  # GET /statuses
  # GET /statuses.json
  def index
    @statuses = Status.all
  end

  # GET /statuses/1
  # GET /statuses/1.json
  def show
  end

  # GET /statuses/new
  def new
    @status = Status.new
  end

  # GET /statuses/1/edit
  def edit
  end

  # POST /statuses
  # POST /statuses.json
  def create
    @status = Status.new(status_params)

    respond_to do |format|
      if @status.save
        format.html { redirect_to @status, notice: 'Status was successfully created.' }
        format.json { render :show, status: :created, location: @status }
      else
        format.html { render :new }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /statuses/1
  # PATCH/PUT /statuses/1.json
  def update
    respond_to do |format|
      if @status.update(status_params)
        format.html { redirect_to @status, notice: 'Status was successfully updated.' }
        format.json { render :show, status: :ok, location: @status }
      else
        format.html { render :edit }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statuses/1
  # DELETE /statuses/1.json
  def destroy
    @status.destroy
    respond_to do |format|
      format.html { redirect_to statuses_url, notice: 'Status was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_status
      @status = Status.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def status_params
      params.require(:status).permit(:user_id, :comment)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def flash_card type
		case type
		when "notice"
			"alert-success"
		when "alert"
			"alert-danger"
		else
			""
		end
	end

end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AppBook</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %> 
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="container" style="padding-top:50px">

	<header>
		<nav class="navbar navbar-default navbar-fixed-top">
		<%= link_to "ESS Soft Core",feed_path,:class=>"navbar-brand" %>
		<ul class="nav navbar-nav pull-right">
		<% if user_signed_in? %>
			<%= link_to image_tag(current_user.gravatar,:class=>"pix-nav img-circle"),current_user.username %>
			<li><%= link_to current_user.fullName,edit_user_registration_path %></li>
			<li><%= link_to "Log OFF",logout_path %></li>
		<% else %>
			<li><%= link_to "Register",register_path %>
			<li><%= link_to "Log IN",login_path %>
		<% end %>
		</ul>

		</nav>
	<header>
	<% flash.each do |type,msg| %>
	<div class="alert <%= flash_card type %>">
		<button class="close" data-dismiss="alert">x</button>
		<%= msg %>
	</div>
	<% end %>
	
<%= yield %>

	<span class="clearfix"></span>
	<footer class="panel panel-default" style="margin-top:50px">
	<div class="panel-heading">
		<p>&copy;All Right Reserved By ESS Indepencies Soft</p>
		</div>
	</footer>
</body>
</html>

app/views/statuses/_form.html.erb
<%= simple_form_for(@status, html: { class: 'form-horizontal' }) do |form|
 %>
  <% if @status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@status.errors.count, "error") %> prohibited this status from being saved:</h2>

      <ul>
      <% @status.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group field">
      <span class="col-md-2"></span>
      <!--  <%= form.label :user_id,:class=>"col-md-2 control-label" %> -->
    <span class="col-md-5">
  <!--     <%= form.text_field :user_id,collection:User.all ,:class=>"form-control" %> -->
      <%= form.input :user_id,collection: User.all,label_method: :fullName %>
    </span>
  </div>
  <div class="form-input field">
    <%= form.label :comment,:class=>"control-label col-md-2" %><br>
    <span class="col-md-5">
      <%= form.text_area :comment,:class=>"form-control" %>
    </span>
  </div>
  <br/>
  <div class="actions clearfix">
    <%= form.submit "Save",class:"btn btn-default" %>
  </div>
<% end %>

app/views/statuses/edit.html.erb
<h1>Editing Status</h1>

<%= render 'form' %>

<div class="btn-group">
<%= link_to 'Show', @status,:class=>"btn btn-default" %>
<%= link_to 'Back', statuses_path,:class=>"btn btn-default" %>
</div>

app/views/statuses/index.html.erb
<h1>Tweets ...</h1>

<div class="col-md-push-8">
<%= link_to '+ Tweet', new_status_path,:class=>"btn btn-default" %>
</div>

<% @statuses.each do |status| %>
  <div class="media row">
    <div class="media-left col-md-1">
      <%= link_to image_tag(status.user.gravatar),status.user.username %>
    </div>
    <div class="media-body col-md-7">
      <h4 class="media-heading"><%= status.user.fullName %></h4>
      <p> <%= status.comment %> </p>
    </div>
    <div class="col-md-3 btn-group hidden">
      <%= link_to time_ago_in_words(status.created_at),status,:class=>"btn btn-sm btn-default" %>
      <%= link_to "EDIT",edit_status_path(status),:class=>"btn btn-sm btn-default" %>
      <%= link_to "DEL",status,method: :delete, data:{confirm:"Are you Sure?"},:class=>"btn btn-sm btn-default" %>
    </div>
  </div>
<% end %>

<script type="text/javascript">
  jQuery.ready( 
  $("div.media.row").hover(function(){ $(this).find("div.col-md-3").toggleClass("hidden") } )
);
</script>

app/views/statuses/new.html.erb
<h1>New Status</h1>

<%= render 'form' %>

<%= link_to 'Back', statuses_path,:class=>"btn btn-default" %>

app/views/statuses/show.html.erb
<div class="panel panel-default">
	<div class="panel-heading">
		<h4>
		  <%= @status.user.fullName %>
		</h4>
	</div>
	<div class="panel-body">
		<p>
		  <%= @status.comment %>
		</p>
	</div>
</div>
<div class="btn-group col-md-push-5">
	<%= link_to 'Edit', edit_status_path(@status),:class=>"btn btn-default" %>
	<%= link_to 'Back', statuses_path,:class=>"btn btn-default" %>
</div>